Adding better message errors
dojot/gui pull request #713
Opened 2021-01-14 20:22 UTC by cfrancisco

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix.

* **What is the current behavior?** (You can also link to an open issue here)
The currently displayed message is not informative when the web service is down.

* **What is the new behavior (if this is a feature change)?**
Now, when the web service is down, shows human-readable errors in the toaster (50X code errors).

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
This PR is related to dojot/dojot#1808.

* **Other information**:

2021-01-15 12:11 UTC, luisfelipefurlan approved these changes

2021-01-15 14:51 UTC, mprevide commented on src/js/comms/util/util.js
> +        console.log("_status", response);
Remove console.log

2021-01-15 14:53 UTC, mprevide requested changes
I just left a minor comment

2021-01-15 16:21 UTC, mprevide approved these changes

2021-01-19 11:27 UTC, luisfelipefurlan approved these changes

2021-01-19 12:18 UTC, merged