Actions
dojot/gui pull request #716
Opened 2021-02-05 15:38 UTC by marianoleonardo

dojot/dojot#1913

2021-02-05 17:15 UTC, mprevide submitted a review, later dismissed
Great job! :+1:

2021-02-05 17:19 UTC, mprevide commented on .github/workflows/main.yml
> +        buildoptions: " --label 'commit_sha'='${{ github.sha }}' "
Change to `buildoptions: ' --label commit_sha_dojot=${{ github.sha }} '` in this yaml and others you will create in other repositories! :)

2021-02-05 17:19 UTC, mprevide commented on .github/workflows/main.yml
> +        buildoptions: " --label 'commit_sha'='${{ github.sha }}' "
I need to fix this in dojot/dojot, dojot/sdk.. and dojot/gui-v2

2021-02-05 17:23 UTC, mprevide commented
Sorry, there is one more details, just in guis, that I forget, you need to pass the arg DOJOT_VERSION.
It's just copy from here the idea:  https://github.com/dojot/gui-v2/blob/b9dcc27be4161efe5ed3edb4d4b19360e72c5165/.github/workflows/gui-v2.yml#L77

2021-02-05 17:26 UTC, mprevide requested changes
I left some comments

2021-02-05 17:55 UTC, mprevide commented on .github/workflows/main.yml
> +      - name: Release Version
Maybe this indentation will case some error

2021-02-05 18:12 UTC, mprevide approved these changes
Great! :1st_place_medal:

2021-02-08 18:48 UTC, thiagodpf approved these changes

2021-02-19 12:47 UTC, merged