[fix] X-axis legend was showing undefined on details
dojot/gui pull request #725
Opened 2021-03-15 16:49 UTC by cfrancisco

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2021-03-16 14:39 UTC, luisfelipefurlan submitted a review, later dismissed

2021-03-16 17:17 UTC, mprevide submitted a review, later dismissed

2021-03-19 13:38 UTC, mprevide requested changes
You got things from development that shouldn't go to v0.6.0 and are not related to your ticket, please remove them

2021-03-19 14:24 UTC, cfrancisco commented
I created another PR removing the merge with development.

2021-03-19 14:24 UTC, closed without merging